Set fifo rate and mpu addr
ElectronicCats/mpu6050 pull request #69
Opened 2023-12-12 16:13 UTC by whyameye

2 small changes to `dmpInitialize()`:

- before this change `dmpInitialize()` would set the FIFO rate at 100hz (hardcoded). This commit adds an optional parameter to set the FIFO rate and defaults to 100hz if no parameter is given. Rate is calculated by `(200/(1+x))` where `x` is the optional parameter and defaults to `1`.
- before this change `dmpInitialize()` assumes the MPU6050 address is 0x68 (hardcoded). This commit adds an optional parameter to set the address and defaults to address 0x68 if no address is given.

slowing down the FIFO rate was my workaround to address issue #16. Theis commit maintains backward compatibility.

2023-12-12 21:18 UTC, sabas1080 requested changes
@whyameye thank you for your contribution, please check the unit tests or the github action, it seems that the structure of the functions has not been completely changed.

2023-12-12 21:46 UTC, whyameye commented
the only failures I'm seeing are all related to the example I pushed in the last PR and that's because that code is specifically written for the LGT8F328p. What am I not seeing specifically?

2023-12-12 21:54 UTC, whyameye commented
oops sorry I see the errors now. I'll look into it.

2023-12-13 18:09 UTC, xpeqex commented
@whyameye 

No worries, we will be waiting for the changes.

2023-12-13 18:28 UTC, whyameye commented
I was too hasty. Still not right even though checks passed. Don't merge yet.

2023-12-13 18:38 UTC, whyameye commented
OK I think this PR is good now. Let me know if you see any other problems.

2023-12-13 18:41 UTC, sabas1080 approved these changes

2023-12-13 22:23 UTC, DeimosHall approved these changes
LGMT

2023-12-13 22:24 UTC, merged